---

# <center>Introdução aos Tensores com PyTorch 2.0</center>

---

## 1. Introdução 📖

<p style='text-align: justify;'>Bem-vindo a este Jupyter Notebook, onde exploraremos o conceito fundamental do PyTorch 2.0 - os tensores.</p>

<p style='text-align: justify;'>O <a href="https://pytorch.org/get-started/pytorch-2.0/" target="_blank">PyTorch</a> é uma biblioteca de aprendizado de máquina de código aberto para Python, desenvolvida principalmente pela equipe de pesquisa de inteligência artificial do <a href="https://web.facebook.com/?_rdc=1&_rdr" target="_blank">Facebook</a>. É usado para aplicações como processamento de linguagem natural e foi projetado para permitir a computação eficiente de tensores com aceleração de GPU.</p>

<p style='text-align: justify;'>Um tensor é uma generalização de vetores e matrizes para um número maior de dimensões e é uma entidade matemática muito importante no aprendizado profundo. No PyTorch, tudo é um tensor. Seja uma imagem, um vetor de recursos, um conjunto de parâmetros de modelo, todos são representados como tensores.</p>

<p style='text-align: justify;'>Neste notebook, vamos mergulhar fundo no mundo dos tensores. Vamos começar com a criação de tensores, entender suas propriedades e operações, e ver como eles são usados no PyTorch para construir modelos de aprendizado profundo.</p>

# 2. FERRAMENTAS UTILIZADAS 🛠

### 2.1 Carga de Pacotes Python

Este Jupyter Notebook utiliza várias bibliotecas Python, cada uma com um propósito específico:

<ol>
  <li><strong>os</strong>: <code>Interage com o sistema operacional, permitindo a manipulação de arquivos e diretórios.</code></li>
  <li><strong>torch</strong>: <code>PyTorch é usado para aprendizado profundo.</code></li>
  <li><strong>warnings</strong>: <code>Emite mensagens de aviso ao usuário.</code></li>
  <li><strong>math e numpy</strong>: <code>Realizam operações matemáticas.</code></li>
</ol>

In [1]:
# Pytorch
import torch

# Ambiente de Desenvolvimento
import os 
import warnings

# Matemática
import math
import numpy as np

In [2]:
# Ignorando avisos desnecessários
warnings.filterwarnings("ignore")

### 2.2 Checando Versões dos Pacotes

In [3]:
print("--= VERSÕES DOS PACOTES UTILIZADOS =--")
print(f"  - Numpy: {np.__version__}")
print(f"  - Pytorch: {torch.__version__}")
print("--= ------------------------------ =--")

--= VERSÕES DOS PACOTES UTILIZADOS =--
  - Numpy: 1.26.0
  - Pytorch: 2.0.1+cu117
--= ------------------------------ =--


### 2.3 Reprodutibilidade dos Experimentos

<p style='text-align: justify;'>A função `set_seed` é usada para definir a semente para geradores de números aleatórios no NumPy e PyTorch. Isso é útil para garantir que os experimentos sejam reproduzíveis, ou seja, que os mesmos resultados sejam obtidos sempre que o código for executado com a mesma semente.</p>

Aqui estão as funcionalidades de cada parte do código:

<ol>
  <li><code>torch.manual_seed(seed)</code>: Define a semente para o gerador de números aleatórios do PyTorch para a CPU.</li>
  <li><code>os.environ['PYTHONHASHSEED'] = str(seed)</code>: Define a semente para as funções hash do Python.</li>
  <li><code>if torch.cuda.is_available()</code>: Verifica se uma GPU está disponível.</li>
  <li><code>torch.cuda.manual_seed_all(seed)</code>: Define a semente para todas as GPUs disponíveis.</li>
  <li><code>torch.backends.cudnn.deterministic = True</code>: Garante que o backend cuDNN use apenas algoritmos determinísticos.</li>
  <li><code>torch.backends.cudnn.benchmark = False</code>: Desativa o uso de um algoritmo de convolução heurístico.</li>
</ol>

A chamada `set_seed(seed=1996)` no final do bloco de código é usada para aplicar a semente definida à função.

In [4]:
def set_seed(seed=1996):
    
    # CPU
    np.random.seed(seed)
    torch.manual_seed(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)
    
    # GPU
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
        torch.backends.cudnn.deterministic = True
        torch.backends.cudnn.benchmark = False
        
# Chamando a função set_seed()
set_seed()

In [5]:
# Dispositivo usado
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Dispositivo usado: {device}")

Dispositivo usado: cpu


## 3. Tensores com Pytorch 🧮

### 3.1 Tensores com Valores Fixos

No PyTorch, `torch.zeros`, `torch.ones` e `torch.full` são funções que retornam tensores preenchidos com valores fixos.

<ol>
  <li>
    <code>torch.zeros(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor</code>: Este método retorna um tensor preenchido com o valor escalar 0, com a forma definida pelo argumento variável <code>size</code>.
  </li>
  <li>
    <code>torch.ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor</code>: Este método retorna um tensor preenchido com o valor escalar 1, com a forma definida pelo argumento variável <code>size</code>.
  </li>
  <li>
    <code>torch.full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor</code>: Este método retorna um tensor de tamanho <code>size</code> preenchido com <code>fill_value</code>.
  </li>
</ol>

Essas funções são úteis para inicializar tensores quando você sabe a forma do tensor, mas não precisa dos valores iniciais. Além disso, elas também são úteis para criar máscaras ou outros tensores auxiliares em seus cálculos.


In [6]:
# Criando um tensor de zeros
torch.zeros(size=(4, 3), dtype=torch.float32)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# Criando um tensor de uns
torch.ones(size=(3, 4), dtype=torch.float32)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
# Criando um tensor de setes
torch.full(size=(2, 7), fill_value=7, dtype=torch.float32)

tensor([[7., 7., 7., 7., 7., 7., 7.],
        [7., 7., 7., 7., 7., 7., 7.]])

### 3.2 Transformando Listas e Arrays Numpy em Tensores e Vice-versa

A capacidade de transformar arrays Numpy e listas em tensores e vice-versa é extremamente útil em muitos cenários. Aqui estão alguns exemplos:

<ol>
  <li>
    <strong>Compatibilidade com bibliotecas existentes</strong>: Muitas bibliotecas de ciência de dados e aprendizado de máquina, como NumPy, Pandas e Scikit-learn, usam arrays NumPy como estrutura de dados principal. Ser capaz de converter facilmente entre tensores PyTorch e arrays NumPy permite que você integre código PyTorch com código que usa essas bibliotecas.
  </li>
  <li>
    <strong>Eficiência de memória</strong>: Ao converter arrays NumPy em tensores PyTorch, o PyTorch tentará usar a mesma memória subjacente que o array NumPy, se possível. Isso pode resultar em economia de memória significativa se você estiver trabalhando com grandes arrays NumPy que você deseja converter em tensores.
  </li>
  <li>
    <strong>Aproveitando recursos do PyTorch</strong>: O PyTorch oferece muitos recursos poderosos, como diferenciação automática e aceleração de GPU, que não estão disponíveis no NumPy. Ao converter arrays NumPy em tensores PyTorch, você pode aproveitar esses recursos.
  </li>
  <li>
    <strong>Manipulação de dados</strong>: As listas são uma estrutura de dados fundamental em Python e são usadas para armazenar coleções de itens. Ser capaz de converter facilmente entre listas e tensores permite que você manipule e processe esses dados usando as operações de tensor do PyTorch.
  </li>
</ol>

In [9]:
# Criando uma lista Python
lista_python = [1, 2, 3, 4]

# Criando um Array Numpy
array_numpy = np.array([1, 2, 3, 4])

In [10]:
# Converte uma lista para tensor
print(f"Lista Python para tensor: {torch.Tensor(lista_python)}")

# Converte um array numpy para tensor
print(f"Array Numpy para tensor: {torch.Tensor(array_numpy)}")

Lista Python para tensor: tensor([1., 2., 3., 4.])
Array Numpy para tensor: tensor([1., 2., 3., 4.])


In [11]:
# Converte um tensor para uma lista Python
print(f"Tensor para lista Python: {torch.Tensor(lista_python).tolist()}")

# Converte um tensor em um Array Numpy
print(f"Tensor para array Numpy: {torch.Tensor(array_numpy).numpy()}")

Tensor para lista Python: [1.0, 2.0, 3.0, 4.0]
Tensor para array Numpy: [1. 2. 3. 4.]


### 3.3 Tensores aleatórios

Os tensores aleatórios são uma parte importante do PyTorch e são usados em muitos cenários, como a inicialização de pesos em redes neurais. Aqui estão algumas funções que você pode usar para criar tensores aleatórios no PyTorch:

<ol>
  <li>
    <code>torch.rand(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor</code>: Esta função retorna um tensor preenchido com números aleatórios uniformemente distribuídos entre 0 e 1.
  </li>
  <li>
    <code>torch.randn(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor</code>: Esta função retorna um tensor preenchido com números aleatórios normalmente distribuídos com média 0 e variância 1.
  </li>
  <li>
    <code>torch.randint(low=0, high, size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor</code>: Esta função retorna um tensor preenchido com inteiros aleatórios gerados uniformemente entre <code>low</code> (inclusive) e <code>high</code> (exclusivo).
  </li>
</ol>

Essas funções são úteis quando você precisa de um tensor com elementos aleatórios. Por exemplo, você pode usar `torch.rand` para inicializar os pesos de uma rede neural com valores aleatórios pequenos, o que é uma prática comum no aprendizado profundo.


In [12]:
# Criando um tensor com valores aleatórios preenchido com números uniformemente distribuídos entre 0 e 1
torch.rand(size=(4, 4), dtype=torch.float32)

tensor([[0.5421, 0.0359, 0.8337, 0.6938],
        [0.2609, 0.2559, 0.3787, 0.4453],
        [0.9004, 0.5096, 0.5480, 0.7183],
        [0.7592, 0.5139, 0.7727, 0.4157]])

In [13]:
# Criando um tensor preenchido com números aleatórios normalmente distribuídos com média 0 e variância 1
torch.randn(size=(4, 5), dtype=torch.float32)

tensor([[-0.6538,  0.6724, -0.5107,  0.6322, -1.6815],
        [ 0.7980, -1.2627,  1.0787, -0.4232, -1.8421],
        [-0.5638, -1.4728,  0.6927, -0.7499, -0.9444],
        [ 0.3950, -1.1509, -1.2043,  0.5978, -0.1458]])

In [14]:
# Criando um tensor preenchido com inteiros aleatórios gerados uniformemente
torch.randint(low=0, high=10, size=(4, 5), dtype=torch.int32)

tensor([[5, 2, 1, 9, 5],
        [8, 4, 6, 6, 2],
        [9, 5, 0, 1, 3],
        [8, 9, 1, 4, 6]], dtype=torch.int32)

### 3.4 Formas de Tensores

A “forma” de um tensor se refere às dimensões do tensor. Por exemplo, um tensor 1D (ou vetor) com comprimento `n` terá a forma `(n,)`. Um tensor 2D (ou matriz) com `m` linhas e `n` colunas terá a forma `(m, n)`. Da mesma forma, um tensor 3D terá a forma `(l, m, n)` e assim por diante.

Aqui estão algumas maneiras de criar tensores com formas específicas no PyTorch:

<ol>
  <li>
    <code>torch.empty(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor</code>: Esta função retorna um tensor preenchido com dados não inicializados. A forma do tensor é definida pelo argumento variável <code>size</code>.
  </li>
  <li>
    <code>torch.empty_like(input, *, dtype=None, layout=None, device=None, requires_grad=False) → Tensor</code>: Esta função retorna um tensor não inicializado com o mesmo tamanho que o <code>input</code>. É equivalente a <code>torch.empty(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)</code>.
  </li>
  <li>
    <code>torch.zeros_like(input, *, dtype=None, layout=None, device=None, requires_grad=False) → Tensor</code>: Esta função retorna um tensor preenchido com o valor escalar 0, com o mesmo tamanho que o <code>input</code>. É equivalente a <code>torch.zeros(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)</code>.
  </li>
  <li>
    <code>torch.ones_like(input, *, dtype=None, layout=None, device=None, requires_grad=False) → Tensor</code>: Esta função retorna um tensor preenchido com o valor escalar 1, com o mesmo tamanho que o <code>input</code>. É equivalente a <code>torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)</code>.
  </li>
  <li>
    <code>torch.rand_like(input, *, dtype=None, layout=None, device=None, requires_grad=False) → Tensor</code>: Esta função retorna um tensor preenchido com números aleatórios de uma distribuição uniforme no intervalo [0, 1), com o mesmo tamanho que o <code>input</code>. É equivalente a <code>torch.rand(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)</code>.
  </li>
</ol>

In [15]:
# Tensor preenchido com dados não inicializados/dados da memória
tensor_empty = torch.empty(size=(2, 5))

# Imprimindo o tensor e suas dimensões
print(f"Tensor\n{tensor_empty}\nDimensões:\n{tensor_empty.shape}")

Tensor
tensor([[ 2.7380e-35,  0.0000e+00,  0.0000e+00,  0.0000e+00,  2.7358e-35],
        [ 0.0000e+00,  2.4726e-36,  0.0000e+00, -9.9467e-14,  4.5663e-41]])
Dimensões:
torch.Size([2, 5])


In [16]:
# Tensor não inicializado equivalente à torch.empty(input.size())
torch.empty_like(tensor_empty)

tensor([[-1.8374e-11,  4.5663e-41,  2.7373e-35,  0.0000e+00,  1.4013e-45],
        [ 0.0000e+00,  2.7341e-35,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [17]:
# Tensor preenchido com o valor escalar 0, equivalente a torch.zeros(input.size())
torch.zeros_like(tensor_empty)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [18]:
# Tensor preenchido com o valor escalar 1, equivalente a torch.ones(input.size())
torch.ones_like(tensor_empty)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [19]:
# Tensor preenchido com valores aleatórios uniformemente distribuido entre [0, 1].
# Equivalente a torch.rand(input.size())
torch.rand_like(tensor_empty)

tensor([[0.6451, 0.9702, 0.4817, 0.0741, 0.5134],
        [0.7750, 0.7207, 0.1815, 0.3376, 0.6172]])

In [20]:
# Tensor preenchido com um valor pré-definido, equivalente a torch.full(input.size())
torch.full_like(tensor_empty, fill_value=7, dtype=torch.int32)

tensor([[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]], dtype=torch.int32)

### 3.5 Tipos de dados tensores

Os tensores do PyTorch são matrizes multidimensionais que contêm elementos de um único tipo de dado. O PyTorch define 10 tipos de tensores com variantes de CPU e GPU. Aqui estão os tipos de dados de tensor disponíveis no PyTorch 2.0:

<ul>
  <li><strong>32-bit floating point</strong>: <code>torch.float32</code> ou <code>torch.float</code></li>
  <li><strong>64-bit floating point</strong>: <code>torch.float64</code> ou <code>torch.double</code></li>
  <li><strong>16-bit floating point [1]</strong>: <code>torch.float16</code> ou <code>torch.half</code></li>
  <li><strong>16-bit floating point [2]</strong>: <code>torch.bfloat16</code></li>
  <li><strong>32-bit complex</strong>: <code>torch.complex32</code> ou <code>torch.chalf</code></li>
  <li><strong>64-bit complex</strong>: <code>torch.complex64</code> ou <code>torch.cfloat</code></li>
  <li><strong>128-bit complex</strong>: <code>torch.complex128</code> ou <code>torch.cdouble</code></li>
  <li><strong>8-bit integer (unsigned)</strong>: <code>torch.uint8</code></li>
  <li><strong>8-bit integer (signed)</strong>: <code>torch.int8</code></li>
  <li><strong>16-bit integer (signed)</strong>: <code>torch.int16</code> ou <code>torch.short</code></li>
  <li><strong>32-bit integer (signed)</strong>: <code>torch.int32</code> ou <code>torch.int</code></li>
  <li><strong>64-bit integer (signed)</strong>: <code>torch.int64</code> ou <code>torch.long</code></li>
  <li><strong>Boolean</strong>: <code>torch.bool</code></li>
</ul>

Cada tipo de tensor tem suas próprias características e usos. Veja alguns exemplos de criação de tensores abaixo:

In [21]:
# Tensor int16
torch.randint(low=0, high=100, size=(2, 5, 5), dtype=torch.int16)

tensor([[[31, 20, 34, 20, 41],
         [ 7, 87,  4, 30, 78],
         [16, 73,  5, 99, 69],
         [50, 84, 95, 83, 44],
         [54, 83, 76,  6, 30]],

        [[89, 25,  3, 50, 66],
         [33, 97, 85, 32, 74],
         [25, 83, 60,  8, 27],
         [59, 43, 26,  8, 19],
         [86, 55,  1, 51, 15]]], dtype=torch.int16)

In [22]:
# Tensor float32
torch.randn(size=(2, 5, 5), dtype=torch.float32)

tensor([[[ 0.9415,  1.1322, -1.0530,  1.1068, -0.0437],
         [-0.2157, -0.2562,  1.1820, -0.2341,  0.7723],
         [ 0.0607, -1.3471,  1.6745,  1.7941, -0.4955],
         [ 1.2411, -0.3938,  2.1914, -1.3212, -0.5561],
         [ 0.5730,  0.1772, -1.9993,  1.1892, -1.4911]],

        [[-0.2772,  0.0374,  0.2431,  0.1902, -0.5840],
         [ 0.1629,  1.5833, -0.1184,  0.5443,  0.3447],
         [-0.7040, -1.3075, -0.6274,  0.5751, -1.4587],
         [ 0.5204, -0.2349, -2.3035,  1.3408,  1.2252],
         [-0.5836,  0.2966,  0.5345, -0.4606,  0.2670]]])

## 4. Matemática e lógica com tensores PyTorch 💡

Os tensores do PyTorch suportam uma ampla variedade de operações matemáticas e lógicas. Aqui estão alguns exemplos:

<ul>
  <li><strong>Operações aritméticas</strong>: As operações aritméticas básicas como adição, subtração, multiplicação e divisão podem ser realizadas em tensores. Além disso, o PyTorch também suporta operações mais complexas como raiz quadrada, exponenciação, logaritmo, etc.</li>
  <li><strong>Operações lógicas</strong>: O PyTorch suporta operações lógicas como AND, OR e XOR em tensores booleanos. Por exemplo, a função <code>torch.logical_and</code> calcula o AND lógico elemento a elemento dos tensores de entrada. Os zeros são tratados como False e os não zeros são tratados como True.</li>
  <li><strong>Indexação, fatiamento, junção, mutação</strong>: O PyTorch suporta várias operações para manipular tensores, incluindo indexação, fatiamento, junção (por exemplo, <code>torch.cat</code>), e mutação (por exemplo, <code>torch.transpose</code>). Essas operações permitem reorganizar, redimensionar, e modificar tensores de várias maneiras.</li>
  <li><strong>Funções matemáticas</strong>: O PyTorch também inclui uma ampla gama de funções matemáticas que podem ser aplicadas a tensores, como funções trigonométricas, funções exponenciais e logarítmicas, etc.</li>
</ul>

Essas operações podem ser usadas para realizar uma ampla variedade de cálculos e são fundamentais para muitos algoritmos de aprendizado de máquina.


### 4.1 Operações Aritméticas

As operações aritméticas são fundamentais quando trabalhamos com tensores no PyTorch. Aqui estão algumas das operações mais comuns:

<ol>
  <li>
    <strong>Adição</strong>: Você pode adicionar dois tensores usando o operador <code>+</code> ou a função <code>torch.add()</code>. Por exemplo, se você tem dois tensores <code>a</code> e <code>b</code>, você pode adicionar os dois usando <code>a + b</code> ou <code>torch.add(a, b)</code>.
  </li>
  <li>
    <strong>Subtração</strong>: A subtração de tensores pode ser realizada usando o operador <code>-</code> ou a função <code>torch.sub()</code>. Por exemplo, <code>a - b</code> ou <code>torch.sub(a, b)</code>.
  </li>
  <li>
    <strong>Multiplicação</strong>: A multiplicação de tensores pode ser feita de várias maneiras, dependendo do que você precisa. A multiplicação elemento a elemento pode ser feita usando <code>a * b</code> ou <code>torch.mul(a, b)</code>. A multiplicação de matrizes pode ser realizada usando <code>torch.matmul(a, b)</code>.
  </li>
  <li>
    <strong>Divisão</strong>: A divisão de tensores pode ser realizada usando o operador <code>/</code> ou a função <code>torch.div()</code>. Por exemplo, <code>a / b</code> ou <code>torch.div(a, b)</code>.
  </li>
</ol>

In [24]:
# Operações aritméticas de um tensor por escalar
print(f'Adição: {torch.ones(size=(1, 4)) + 1}')
print(f'Subtração: {torch.ones(size=(1, 4)) - 1}')
print(f'Multiplicação: {torch.ones(size=(1, 4)) / 2}')
print(f'Exponenciação: {torch.ones(size=(1, 4)) ** 1/5}')

Adição: tensor([[2., 2., 2., 2.]])
Subtração: tensor([[0., 0., 0., 0.]])
Multiplicação: tensor([[0.5000, 0.5000, 0.5000, 0.5000]])
Exponenciação: tensor([[0.2000, 0.2000, 0.2000, 0.2000]])


In [25]:
# Criando tensores
t1 = torch.full(size=(1, 5), fill_value=4.5, dtype=torch.float32)
t2 = torch.randn_like(t1)

# Operações artiméticas entre tensores
print(f'Adição: {t1}+{t2}={t1 + t2}\n')
print(f'Subtração: {t1}+{t2}={t1*t2}\n')
print(f'Multiplicação: {t1}/{t2}={t1/t2}\n')
print(f'Exponenciação: {t1}^{t2}={t1**t2}')

Adição: tensor([[4.5000, 4.5000, 4.5000, 4.5000, 4.5000]])+tensor([[-0.8075,  0.4227,  1.2055, -1.4151, -1.9007]])=tensor([[3.6925, 4.9227, 5.7055, 3.0849, 2.5993]])

Subtração: tensor([[4.5000, 4.5000, 4.5000, 4.5000, 4.5000]])+tensor([[-0.8075,  0.4227,  1.2055, -1.4151, -1.9007]])=tensor([[-3.6340,  1.9023,  5.4249, -6.3679, -8.5531]])

Multiplicação: tensor([[4.5000, 4.5000, 4.5000, 4.5000, 4.5000]])/tensor([[-0.8075,  0.4227,  1.2055, -1.4151, -1.9007]])=tensor([[-5.5724, 10.6449,  3.7328, -3.1800, -2.3676]])

Exponenciação: tensor([[4.5000, 4.5000, 4.5000, 4.5000, 4.5000]])^tensor([[-0.8075,  0.4227,  1.2055, -1.4151, -1.9007]])=tensor([[0.2968, 1.8886, 6.1302, 0.1190, 0.0573]])


### 4.2 Manipulando formas de tensor

Trabalhar com tensores em PyTorch muitas vezes envolve manipular suas formas. Aqui estão algumas das operações mais comuns:

<ol>
  <li>
    <strong>Reshape</strong>: A função <code>torch.reshape()</code> pode ser usada para reorganizar os elementos de um tensor para se ajustar a uma determinada forma. Por exemplo, se você tem um tensor de forma <code>(4, 2)</code> e deseja reorganizá-lo para a forma <code>(2, 4)</code>, você pode usar <code>torch.reshape(tensor, (2, 4))</code>.
  </li>
  <li>
    <strong>Squeeze e Unsqueeze</strong>: <code>torch.squeeze()</code> remove as dimensões de tamanho 1 do tensor, enquanto <code>torch.unsqueeze()</code> adiciona uma dimensão extra de tamanho 1. Isso é útil para adicionar ou remover dimensões que são necessárias para certas operações.
  </li>
  <li>
    <strong>Flatten</strong>: <code>torch.flatten()</code> é usado para transformar o tensor em um tensor 1D. Isso é útil quando você quer transformar um tensor multidimensional em um vetor.
  </li>
  <li>
    <strong>Permute e Transpose</strong>: <code>torch.permute()</code> permite reordenar as dimensões de um tensor de qualquer maneira que você quiser. <code>torch.transpose()</code> é um caso especial disso, onde duas dimensões são trocadas. Isso é comumente usado para trocar as dimensões de altura e largura em imagens.
  </li>
  <li>
    <strong>Size e Shape</strong>: <code>tensor.size()</code> e <code>tensor.shape</code> retornam o tamanho do tensor. <code>tensor.numel()</code> retorna o número total de elementos no tensor.
  </li>
</ol>

In [26]:
# Criando Tensor
t = torch.randn(size=(4, 3), dtype=torch.float32)
print(t)

tensor([[ 2.5634, -1.2311, -0.8583],
        [ 1.1428,  1.3181, -0.1957],
        [-0.6026,  0.1019, -0.1568],
        [ 0.3462, -0.7328,  1.1331]])


In [27]:
# Adiciona uma dimensão extra de tamanho 1
t.unsqueeze(dim=(0))

tensor([[[ 2.5634, -1.2311, -0.8583],
         [ 1.1428,  1.3181, -0.1957],
         [-0.6026,  0.1019, -0.1568],
         [ 0.3462, -0.7328,  1.1331]]])

In [28]:
# Dimensões do tensor
print("Original: ",t.shape)
print("unsqueeze:", t.unsqueeze(dim=(0)).shape)

Original:  torch.Size([4, 3])
unsqueeze: torch.Size([1, 4, 3])


In [29]:
# Usando reshape
t.reshape((1, 4, 3))

tensor([[[ 2.5634, -1.2311, -0.8583],
         [ 1.1428,  1.3181, -0.1957],
         [-0.6026,  0.1019, -0.1568],
         [ 0.3462, -0.7328,  1.1331]]])

In [30]:
# Achatando um tensor nD para 1D
t.flatten()

tensor([ 2.5634, -1.2311, -0.8583,  1.1428,  1.3181, -0.1957, -0.6026,  0.1019,
        -0.1568,  0.3462, -0.7328,  1.1331])

### 4.3 Fatiamento/Slicing de Tensores

O fatiamento, ou slicing, é uma técnica essencial ao trabalhar com tensores no PyTorch. Esta operação permite acessar e manipular partes específicas de um tensor de forma eficiente e intuitiva.

Semelhante às listas e arrays em Python, o PyTorch permite o fatiamento de tensores. Por exemplo, em um tensor bidimensional (uma matriz), é possível acessar um elemento específico fornecendo os índices da linha e da coluna. Além disso, é possível acessar uma linha ou coluna inteira de uma matriz usando a técnica de fatiamento.

O fatiamento é uma ferramenta poderosa que facilita a manipulação e o acesso aos dados dos tensores. Com a prática, você descobrirá muitos usos para o fatiamento ao trabalhar com tensores no PyTorch.

In [33]:
# Cria tensor de inteiros uniformemente distribuídos
tensor_int = torch.randint(low=0, high=10, size=(7, 5))
print(tensor_int)

tensor([[3, 9, 5, 3, 5],
        [0, 6, 7, 7, 9],
        [4, 4, 0, 2, 7],
        [9, 8, 2, 1, 2],
        [1, 4, 9, 7, 5],
        [6, 9, 0, 4, 1],
        [7, 7, 6, 5, 2]])


In [32]:
# Primeira linha
tensor_int[0, :]

tensor([9, 1, 5, 3, 8])

In [34]:
# Primeira coluna
tensor_int[:,0]

tensor([3, 0, 4, 9, 1, 6, 7])

In [36]:
# As duas primeiras linhas
tensor_int[0:2, :]

tensor([[3, 9, 5, 3, 5],
        [0, 6, 7, 7, 9]])

In [37]:
# As duas primeiras colunas
tensor_int[:,0:2]

tensor([[3, 9],
        [0, 6],
        [4, 4],
        [9, 8],
        [1, 4],
        [6, 9],
        [7, 7]])

In [39]:
# As duas últimas linhas
tensor_int[-2:, :]

tensor([[6, 9, 0, 4, 1],
        [7, 7, 6, 5, 2]])

In [40]:
# As duas últimas colunas
tensor_int[:, -2:]

tensor([[3, 5],
        [7, 9],
        [2, 7],
        [1, 2],
        [7, 5],
        [4, 1],
        [5, 2]])